[test]
pathIgnorePatterns = ["fixtures/**", "fixture/**"]
coverage = true
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["src/test-setup.ts"]
concurrentTestGlob = "**/*.test.ts"
onlyFailures = true

[install]
linker = "isolated"

[run]
bun = true
